/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Matrix */

#ifndef _Included_Matrix
#define _Included_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Matrix
 * Method:    multiplyC
 * Signature: ([D[D[DIII)V
 */
JNIEXPORT void JNICALL Java_Matrix_multiplyC
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     Matrix
 * Method:    powerC
 * Signature: (I[D[DI)V
 */
JNIEXPORT void JNICALL Java_Matrix_powerC
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
